version: '2.1'

networks:
  front:
    external: true
    name: 'host'
  back:
    external: true
    name: 'host'
  default:
    external: true
    name: 'host'

services:
  web:
    network_mode: host
    extra_hosts: 
      - "influxdb:127.0.0.1"
  grafana:
    environment:
      GF_DATABASE_HOST: ${GF_DATABASE_HOST:-127.0.0.1}
    network_mode: host
    extra_hosts: 
      - "influxdb:127.0.0.1"
  db_grafana:
    network_mode: host
    volumes:
      - ./mysql/local-binding.cnf:/etc/mysql/conf.d/local-binding.cnf
  influxdb:
    network_mode: host
    environment:
      INFLUXDB_UDP_BIND_ADDRESS: "127.0.0.1:8089"
      INFLUXDB_HTTP_BIND_ADDRESS: "127.0.0.1:8086"

